// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq74kSe2-qWy-_3qjHEYj6Kc-GLwOvRoM',
    appId: '1:608562815287:web:917ec040646837232c3ab2',
    messagingSenderId: '608562815287',
    projectId: 'evently-app-ef5ff',
    authDomain: 'evently-app-ef5ff.firebaseapp.com',
    storageBucket: 'evently-app-ef5ff.firebasestorage.app',
    measurementId: 'G-3H6VGMPL12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJdvNbLbOgSXgUPuO3DBpheRaVEkLyihQ',
    appId: '1:608562815287:android:d1f78b41dac3c2c62c3ab2',
    messagingSenderId: '608562815287',
    projectId: 'evently-app-ef5ff',
    storageBucket: 'evently-app-ef5ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBedXT5KiIXSBkFKuvI5HvR8SyGn6OQLb4',
    appId: '1:608562815287:ios:30982b75abc006172c3ab2',
    messagingSenderId: '608562815287',
    projectId: 'evently-app-ef5ff',
    storageBucket: 'evently-app-ef5ff.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBedXT5KiIXSBkFKuvI5HvR8SyGn6OQLb4',
    appId: '1:608562815287:ios:30982b75abc006172c3ab2',
    messagingSenderId: '608562815287',
    projectId: 'evently-app-ef5ff',
    storageBucket: 'evently-app-ef5ff.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq74kSe2-qWy-_3qjHEYj6Kc-GLwOvRoM',
    appId: '1:608562815287:web:8cc7089db55b21452c3ab2',
    messagingSenderId: '608562815287',
    projectId: 'evently-app-ef5ff',
    authDomain: 'evently-app-ef5ff.firebaseapp.com',
    storageBucket: 'evently-app-ef5ff.firebasestorage.app',
    measurementId: 'G-D3XH6R50GH',
  );
}
